# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827b874d05c7f4d26d1e7ff2b63bafbda9eecd45022b526d486a25be1e49b83a2ed3780d59d365909a33f82e8696e7becaada3ebcd34047aaead4dfc88111bc3

test:
  secret_key_base: ef187d755fd345d3582d2817458f4f1e57f0deabdcc2bccddc67c8d23640855e22dc4ba89f7af544628ba31952e8b964ec6a1db55a91c8ea756a5096c4a14c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
